---

- hosts: all


  tasks:

  - name: apt-get update && apt-get dist-upgrade
    apt:
      update_cache: yes	
      upgrade: dist

  - name: apt-get autoclean
    apt:
      autoclean: yes

  - name: apt-get autoremove
    apt:
      autoremove: yes
